### ISSUE TITLE
Consideracoes

### ISSUE THREAD

**Issue by IgorDePaula** [me42th/remote-shell#1]
1- <del>da uma lida nesse link: https://laravel.com/docs/9.x/packages#package-discovery . A partir do laravel 7, voce pode usar o composer para fazer a adicao do seu service provider no ecossistema do laravel.</del>

2- trave uma versao minima do laravel e do php.

3- <del>separe os arquivos em estrutura laravel, pra ficar mais organizado: config no config, route no route (afinal, seu pacote pode ter mais de uma rota - web, api etc).</del>

4- <del>o gitignore ficou sem o ponto no inicio, faz diferenca.</del>

5- <del>use uma funcao pra gerar o remote token, deixar fixo voce pode deixar os instalacoes inseguras, uma vez que eu conheco o token pelo repositorio.</del>

6- eh interessante tambem criar testes automatizados, isso da visibilidade, inclusive internacional.

**Comment by IgorDePaula** [comment]
7- outra coisa, da uma melhorada na numeracao da release, da pra fazer isso com gtihub actions e uma lib chamada semantic release, da pra criar os pacotes ate zipados tb.

**Comment by me42th** [comment]
Travar versão, testes automatizados e melhoria no versionamento serão tratados na release v0.0.3
